### ISSUE TITLE
XssFilterTest 예외상황 발생

### ISSUE THREAD

**Issue by psam1017** [devNana222/hhplus0011#16]
[XssFilterTest](https://github.com/devNana222/hhplus0011/blob/feature/step9/hhplus0011/src/test/java/com/tdd/ecommerce/common/filter/XSSFilterTest.java)

위 코드가 실패하는데, 어떻게 XssFilter 기능을 테스트하면 좋을지에 대한 이야기입니다

```
        mockMvc.perform(patch("/customers/1/balance/charge")
                      //  .content("comment", "<script>alert('XSS');</script>"))
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{ \"comment\": \"<script>alert('XSS');</script>\", \"balance\": 1000 }"))
                .andExpect(status().is4xxClientError())
                .andExpect(content().string(not(containsString("<script>alert('XSS');</script>"))))
                .andExpect(content().string(not(containsString("<script>"))))
                .andExpect(content().string(containsString("& lt;")));
```

**Comment by psam1017** [comment]
content() 메서드는 MockMvcResultMatchers 의 메서드로서, response 의 응답값을 보는 내용입니다. 그래서 응답값에 script 가 포함되지 않아서 이 검증이 실패할 수 있을 것 같아요.

저는 mockMvc 로 XssFilter 를 테스트하는 방법을 찾지는 못 했습니다.

**Comment by devNana222** [comment]
웹에서 직접 호출했을 때에는 정상적으로 filter가 걸리는데 테스트를 할 때에는 적용이되지 않습니다.

**Comment by psam1017** [comment]
Request 의 코드 중간에 script 가 변경되었는지를 봐야 하는데, 결과값으로 그 변경된 코드가 넘어오지 않으면

**Comment by psam1017** [comment]
Request 의 코드 중간에 script 가 변경되었는지를 봐야 하는데, 결과값으로 그 변경된 코드가 넘어오지 않으면 테스트가 어려운데, 그렇다고 테스트하자고 API 를 만드는 건, 불필요한 과정이 될 수는 있습니다.

**Comment by psam1017** [comment]
저는 [이렇게 테스트](https://github.com/psam1017/hhplus-ecommerce/pull/13/files#diff-3e7c6ccd4d29c8d33956a4707528a766029e7bccdca27464cd2185e32cd016a0)했어요
